# Copyright 2025 PKU-Alignment Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# ============================================
# 评测配置：
#   - 数据集hf路径
#   - 数据集split
#   - 数据集size
#   - 数据集模态
#   - 评测方式（multiple choice / generation / ...）
#   - 评测指标（accuracy / ...）
#   - 是否支持few_shot
#   - 选项编号形式（ABCD或1234...），判断对错时的标识(true/false或者1/0...)
# ============================================
dataset:
  name: HumanEval
  path: openai/openai_humaneval
  split: test
  size: null
  modality: text-to-text
  fewshot_data_path: openai/openai_humaneval
  fewshot_data_file: null
  fewshot_data_split: test
  cot_fewshot_data_path: benchmarks/cot_fewshot
  cot_fewshot_data_file: null
  cot_fewshot_data_split: null
  max_shot: 5
  default_task_list: ["openai_humaneval"]

task:
  - name: openai_humaneval
    data_files: null
    type: CodeGeneration
    question_key: prompt
    ground_truth_key: canonical_solution
    has_metadata:  True
    candidate_labels: null
    avalable_evaluate_tools: ["extract_first_code_block", "extract_last_code_block"]
    language: python
answer_extractor:
  - name: extract_first_code_block
    function: regex_match_code
    args:
      match_index: 0
  - name: extract_last_code_block
    function: regex_match_code
    args:
      match_index: -1
metrics:
  - name: pass_rate
    function: pass_rate
    args:
      k: 1
overall_metrics:
  - name: null
    function: null
    args:
      null
